// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  biography: dynamic(() => import("./Biography")),
  contact_form: dynamic(() => import("./ContactForm")),
  content_index: dynamic(() => import("./ContentIndex")),
  experience: dynamic(() => import("./Experience")),
  hero3_d: dynamic(() => import("./Hero3D")),
  image_block: dynamic(() => import("./ImageBlock")),
  resume: dynamic(() => import("./Resume")),
  tech_list: dynamic(() => import("./TechList")),
  text_block: dynamic(() => import("./TextBlock")),
};
